### ISSUE TITLE
Consolidate FOIA information

### ISSUE THREAD

**Issue by hbillings** [18F/pclob#11]
Currently, FOIA info is scattered across a variety of pages. It should be consolidated into a single place, location TBD.

**Comment by hbillings** [comment]
@toolness, if you want to do this, the person you need to get in touch with is Mason Clutter, mclutter@pclob.gov (publicly available on their website currently)

**Comment by toolness** [comment]
I added *a* FOIA page in #40, but it largely replicates the legacy site's FOIA page, with the exception that information on submitting a FOIA request is shown at the top of the page. I'm not sure if this is what the PCLOB folks ultimately want, though, so I'm not going to close this issue just yet.
