### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by toolness** [18F/pclob#14]
@hbillings suggested using [lunr.js](https://lunrjs.com/) for this.

It looks like the [18F Content Guide](https://content-guide.18f.gov/) uses an 18F-built, lunr-based jekyll plugin called [`jekyll_pages_api_search`](https://github.com/18F/jekyll_pages_api_search) to provide its search functionality. It looks like the plugin glues together Jekyll and lunr.js, but it should be noted that this requires node on the system that builds the static site. Since I *think* the content guide is hosted by Federalist, I think this means that Federalist has no problem with it. 

One nice thing about the Jekyll plugin for development, which I noticed while working on https://github.com/18F/content-guide/pull/183, is that it "gracefully degrades" if node isn't present, so that way anyone who wants to work on the site locally but doesn't have node installed can still do so--they just won't have working search functionality, which might not be a deal-breaker depending on the context.

Another newer-looking JS search library I just found out about is [wade](https://github.com/KingPixil/wade), but from reading the docs it seems like it's intended more for real-time search along the lines of an auto-complete UI, rather than for full-text search. There's no mention of stemming, for instance (although for that matter, I don't know if lunr.js does stemming).

Anyways, aside from that, though, I do have some user research related questions about this functionality. I think that during the kick-off meeting, the PCLOB folks mentioned that one of the frustrations they had with the current search functionality on their site (which appears to be powered by search.usa.gov) is that people rarely find what they're looking for with it. So I'm curious what kinds of things they're actually searching *for*; if we know that, we can potentially optimize for PCLOB's use cases, and avoid simply recreating the same search problems on a different implementation.

**Comment by toolness** [comment]
Update: just confirmed with Seppi that the Federalist docker containers that build Jekyll sites do indeed have Node on them, so we're safe there.

**Comment by hbillings** [comment]
Awesome research! I wonder if the issues with PCLOB are currently due to the fact that all their content (basically) is in PDF form and they're less searchable? It'd be good to confirm for sure.

Also, it's worth noting that with the `jekyll_pages_api_search` gem, the version of jekyll has to be pinned at 3.1 for unknown reasons. The whole thing blows up otherwise. I tried to chase this down when I was working on the `guides-style` gem, but I could never figure it out.

**Comment by toolness** [comment]
Ah good point, I bet that the PDF's have something to do with it! Like you said though, it'd be good to confirm for sure.

That is a bummer about that gem only being compatible w/ Jekyll 3.1, thanks for mentioning it. I'll see if I can root out the cause and maybe issue a PR to that project that improves its compatibility... if not, I guess we can roll our own thing.

**Comment by toolness** [comment]
Huh, out of curiosity, what version of Jekyll was the site you were developing when working on the `guide-style` gem using?  I'm looking at https://github.com/18F/jekyll_pages_api_search/pull/41, which is an abandoned WIP for adding Jekyll 3.2+ support to the gem, and Will Slack mentions in a comment that 18f.gsa.gov seems to work fine with the gem, and it uses Jekyll 3.3 (for reference, this site's search functionality is only available at https://18f.gsa.gov/blog/).

So now I'm wondering if the gem is incompatible with Jekyll 3.2, but somehow compatible with 3.3, or something weird like that... Maybe changes made in 3.2 were reverted in 3.3?

**Comment by toolness** [comment]
Since #19 is merged and search seems to work okay right now, I'm going to close this issue.
