### ISSUE TITLE
Ensure Google Analytics is properly set up

### ISSUE THREAD

**Issue by toolness** [18F/pclob#35]
It looks like the settings are in `_config.yml` and there is already a PCLOB agency set up in DAP.

This metadata feeds into the generation of script tags in `_includes/javascript.html`.

The `analytics.google.code` key in `_config.yml` is for 18F's GA account (as opposed to DAP) and the tracking code we've currently got in there (which I think came w/ the Jekyll template) is for "Federalist Sites". We might want to get a separate tracking code specifically for PCLOB in the `#g-analytics` Slack channel, as explained in https://github.com/18f/analytics-standards.

Also, we need to give the PCLOB folks some sort of official statement that these analytics aren't tracking IP addresses.

**Comment by hbillings** [comment]
So I'm still confused about what needs to be done here. >_< Help me, @toolness, you're my only hope!
