### ISSUE TITLE
Ensure site works when site.baseurl is non-empty

### ISSUE THREAD

**Issue by toolness** [18F/pclob#45]
Jekyll makes this a bit annoying to do, IMO, but we should make sure the site works properly when `site.baseurl` is non-empty. This means prepending  `site.baseurl` to intra-site links, for the most part, i.e. not assuming that `/` is the root of the site.

Ordinarily this might not be a big deal, but because federalist's branch builds *do* set `site.baseurl` to a non-empty value, we need to make sure this works--otherwise federalist branch builds will be useless!

**Comment by toolness** [comment]
Also, a good way to test this locally is to temporarily set `baseurl` in `_config.yml` to something like `/boop`, then run the Jekyll server and visit `http://localhost:4000/boop/` and make sure everything works.

**Comment by hbillings** [comment]
This is currently breaking URLs on some PDF downloads. :-( The "history and mission" page, for instance. I haven't had time to look at the codebase, so I don't know if just prepending the baseurl would fix it.

**Comment by toolness** [comment]
I'm gonna say this was fixed by #85. The remaining 404s will be resolved once we fix #83.
