### ISSUE TITLE
Add Elisebeth B. Collins' June 27, 2017 testimony

### ISSUE THREAD

**Issue by toolness** [18F/pclob#88]
From #79:

Add the following, June 27, 2017—“Board Member Elisebeth Collins’ Testimony before the Senate Judiciary Committee for a Hearing Titled, “ The FISA Amendments Act: Reauthorizing America’s Vital National Security Authority and Protecting Privacy and Civil Liberties.” Include the attached link of her testimony.

[SJC Collins Testimony 6-27-17 final.pdf](https://github.com/18F/pclob/files/1300998/SJC.Collins.Testimony.6-27-17.final.pdf)

**Comment by pmcgill49** [comment]
Fixed by #94
